version: "3.2"

services:
  walker-1:
    build: walker
    container_name: NAS-1
    hostname: NAS-1
    environment:
      - FOLDER_WALKER=TRUE
      - BACKEND_NAME=NAS-1
      - DB_URL=mongodb://macmini2:27017/
      - DB_NAME=media
      - DB_COLLECTION=media_collection
      - PUSH_COLLECTION=push_subscriptions
    volumes:
      - ./src:/src:ro
      - /volume2/Media:/Media:rw
    restart: unless-stopped
    extra_hosts:
        - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
