version: "3.11"

services:
  backend-1:
    build: backend
    container_name: Mini-1
    hostname: Mini-1
    environment:
      - MAIN_BACKEND=FALSE
      - BACKEND_NAME=Mini-1
    volumes:
      - ./src_backend:/src:ro
      - /Volumes/Media:/Media:rw
    restart: "no"
    extra_hosts:
        - "host.docker.internal:host-gateway"

  backend-2:
    build: backend
    container_name: Mini-2
    hostname: Mini-2
    environment:
      - MAIN_BACKEND=FALSE
      - BACKEND_NAME=Mini-2
    volumes:
      - ./src_backend:/src:ro
      - /Volumes/Media:/Media:rw
    restart: "no"
    extra_hosts:
        - "host.docker.internal:host-gateway"

  backend-3:
    build: backend
    container_name: Mini-3
    hostname: Mini-3
    environment:
      - MAIN_BACKEND=FALSE
      - BACKEND_NAME=Mini-3
    volumes:
      - ./src_backend:/src:ro
      - /Volumes/Media:/Media:rw
    restart: "no"
    extra_hosts:
        - "host.docker.internal:host-gateway"

