version: "3.11"

services:
  backend-1:
    build: backend
    container_name: MB-1
    hostname: MB-1
    environment:
      - MAIN_BACKEND=FALSE
      - BACKEND_NAME=MB-1
      - DB_URL=mongodb://SteveDS920:27018/
      - DB_NAME=media
      - DB_COLLECTION=media_collection
    volumes:
      - ./src_backend:/src:ro
      - /Volumes/Media:/Media:rw
    restart: "no"
    extra_hosts:
        - "host.docker.internal:host-gateway"

  backend-2:
    build: backend
    container_name: MB-2
    hostname: MB-2
    environment:
      - MAIN_BACKEND=FALSE
      - BACKEND_NAME=MB-2
      - DB_URL=mongodb://SteveDS920:27018/
      - DB_NAME=media
      - DB_COLLECTION=media_collection
    volumes:
      - ./src_backend:/src:ro
      - /Volumes/Media:/Media:rw
    restart: "no"
    extra_hosts:
        - "host.docker.internal:host-gateway"

  backend-3:
    build: backend
    container_name: MB-3
    hostname: MB-3
    environment:
      - MAIN_BACKEND=FALSE
      - BACKEND_NAME=MB-3
      - DB_URL=mongodb://SteveDS920:27018/
      - DB_NAME=media
      - DB_COLLECTION=media_collection
    volumes:
      - ./src_backend:/src:ro
      - /Volumes/Media:/Media:rw
    restart: "no"
    extra_hosts:
        - "host.docker.internal:host-gateway"

