version: "3.11"

services:
  backend-1:
    build: backend
    container_name: backend-1
    hostname: backend-1
    environment:
      - MAIN_BACKEND=FALSE
      - BACKEND_NAME=BE-1
    volumes:
      - ./src_backend:/src:ro
      - /Volumes/Media:/Media:rw
    restart: "no"
    extra_hosts:
        - "host.docker.internal:host-gateway"

  backend-2:
    build: backend
    container_name: backend-2
    hostname: backend-2
    environment:
      - MAIN_BACKEND=FALSE
      - BACKEND_NAME=BE-2
    volumes:
      - ./src_backend:/src:ro
      - /Volumes/Media:/Media:rw
    restart: "no"
    extra_hosts:
        - "host.docker.internal:host-gateway"

  backend-3:
    build: backend
    container_name: backend-3
    hostname: backend-3
    environment:
      - MAIN_BACKEND=FALSE
      - BACKEND_NAME=BE-3
    volumes:
      - ./src_backend:/src:ro
      - /Volumes/Media:/Media:rw
    restart: "no"
    extra_hosts:
        - "host.docker.internal:host-gateway"

  backend-4:
    build: backend
    container_name: backend-4
    hostname: backend-4
    environment:
      - MAIN_BACKEND=FALSE
      - BACKEND_NAME=BE-4
    volumes:
      - ./src_backend:/src:ro
      - /Volumes/Media:/Media:rw
    restart: "no"
    extra_hosts:
        - "host.docker.internal:host-gateway"
