version: "3.2"

services:
  backend-1:
    build: backend
    container_name: NAS-1
    hostname: NAS-1
    environment:
      - MAIN_BACKEND=FALSE
      - BACKEND_NAME=NAS-1
      - DB_URL=mongodb://macmini2:27017/
      - DB_NAME=media
      - DB_COLLECTION=media_collection
    volumes:
      - ./src_backend:/src:ro
      - /Volumes/Media:/Media:rw
    restart: "no"
    extra_hosts:
        - "host.docker.internal:host-gateway"
