version: "3.11"

services:
  backend-1:
    build: backend
    container_name: MBP-1
    hostname: MBP-1
    environment:
      - MAIN_BACKEND=TRUE
      - BACKEND_NAME=MBP-1
      - DB_URL=mongodb://mongodb:27017/
      - DB_NAME=media
      - DB_COLLECTION=media_collection
    depends_on:
      - mongodb
    volumes:
      - ./src_backend:/src:ro
      - /Users/steve/Downloads/Media:/Media:rw
    restart: "no"
    extra_hosts:
        - "host.docker.internal:host-gateway"

  frontend:
    build: frontend
    hostname: frontend
    environment:
      - DB_URL=mongodb://mongodb:27017/
      - DB_NAME=media
      - DB_COLLECTION=media_collection
    depends_on:
      - mongodb
    volumes:
      - ./src_frontend:/src:ro
    ports:
      - 8020:8020
    restart: "no"
    extra_hosts:
        - "host.docker.internal:host-gateway"

  mongodb:
    image: mongo
    hostname: mongodb
    ports:
      - 27017:27017
    volumes:
      - db_volume:/data/db:rw
      - db_conf:/data/configdb:rw
    restart: "no"
    
volumes:
  db_volume:
  db_conf:
