# Settings for the mongo database
[mongo]
    # The URI of the MongoDB server
    uri = "mongodb://mongodb:27017/"

    # The database and collection to store the data in
    database = "media"
    media_collection = "media_collection"

# Folder definitions
[folders]
    # The path to the folders to scan
    include = [
        "/Media",
    ]

    # The path to folders to exclude from the scan
    exclude = [
        "/Media/Films/VR",
    ]

    # Folder to backup converted files to be checked before deletion
    backup = "/Backup"

# Schedule definitions
[schedule]
    # The timezone to use for the schedule, all of the following times are in this timezone
    timezone = "Europe/London"

    # The time to run the folder scan and update the database
    scan_time = 00:00:00

    # The time to start running the conversion process
    start_conversion_time = 01:00:00

    # The time to stop running the conversion process
    end_conversion_time = 19:00:00
