# Folder definitions
[folders]
    # The path to the folders to scan
    include = [
        "/Media/TV",
        "/Media/Films",
    ]

    # The path to folders to exclude from the scan
    exclude = [
        "/Media/Films/VR",
    ]

    # Folder to backup converted files to be checked before deletion
    backup = "/Media/Backup"

    # Temporary folder for conversions
    conversions = "/Conversions"

# Schedule definitions
[schedule]
    # The timezone to use for the schedule, all of the following times are in this timezone
    timezone = "Europe/London"

    # The time to run the folder scan and update the database
    scan_time = 00:00:00

    # The time to start running the conversion process
    start_conversion_time = 00:05:00

    # The time to stop running the conversion process
    end_conversion_time = 23:59:00

# Encoding settings
[encoding]
    video_codec = "libx265"
    small_height_threshold = 600
    x265_crf = 28
    x265_crf_small_height = 23
    x265_preset = "medium"
    vt_qv = 45
    vt_qv_small_height = 50

# Runtime settings
[runtime]
    log_directory = "/tmp/convert-to-h265/logs"
    secrets_dir = "src/secrets"

# Path mapping settings
[path_map]
    from = "/Media"
    to = "/Media"
